import numpy as np
print("Array(2,9): \n",np.random.rand(2,9))
a1 = np.random.normal(7,5,(4,3))
print("Normal distribution: \n",a1)
b2 = np.random.uniform(2,4,(4,3))
print("Uniform distribution: \n",b2)
c3=  np.random.standard_normal((4,3))
print("Standart-normal distribution: \n",c3)
d4 = np.random.zipf(4,(4,3))
print("Zipf distribution: \n",d4)
print("Rounded normal distribution",np.around(a1,decimals=2))
print("Max: ",a1.max(),", min: ",a1.min())
print("Mean of the 2nd row: ",a1[1,:].mean(),", Mean of the last column: ",a1[:,-1:].mean())
print("fix(): \n",np.fix(a1))
print("rint(): \n",np.rint(a1))
arr = np.random.randint(100000,1000000,(4,4))
print("Random:\n",arr)
print("Rounded:\n",np.round(arr,-3))